[character]
symbol = "➜"
style_success = "bold green"
style_failure = "bold red"

[directory]
truncation_length = 5
truncate_to_repo = true

[git_branch]
symbol = " "

[git_commit]
only_detached = false

[hostname]
ssh_only = true

[line_break]
disabled = false
